# Generated by Django 4.2.5 on 2023-09-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_premiermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
