# Generated by Django 4.2.5 on 2023-09-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_band_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='sexe',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
