# Generated by Django 4.2.5 on 2023-09-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_band_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
