# Generated by Django 4.2.5 on 2023-09-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_band_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='mail',
            field=models.EmailField(default='user@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
