# Generated by Django 4.2.5 on 2023-09-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_band_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='moyenne',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
