# Generated by Django 4.2.5 on 2023-09-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_band_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='admis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='band',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
