# Generated by Django 4.2.5 on 2023-09-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_band_pension'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='rang',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
