# Generated by Django 4.2.5 on 2023-10-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_band_rang'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Band',
            new_name='Etudiant',
        ),
    ]
