# Generated by Django 4.2.5 on 2023-10-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_rename_band_etudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('sexe', models.CharField(max_length=1)),
                ('date_embauche', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('matiere', models.CharField(max_length=100)),
                ('anciennete', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='PremierModel',
        ),
    ]
