# Generated by Django 4.2.5 on 2023-10-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_enseignant_delete_premiermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enseignant',
            new_name='EnseignantPricipale',
        ),
    ]
