# Generated by Django 4.2.5 on 2023-10-15 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_rename_enseignant_enseignantpricipale'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.enseignantpricipale'),
        ),
    ]
