# Generated by Django 4.2.5 on 2023-10-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_etudiant_enseignant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignantpricipale',
            name='anciennete',
        ),
        migrations.RemoveField(
            model_name='enseignantpricipale',
            name='image',
        ),
        migrations.RemoveField(
            model_name='enseignantpricipale',
            name='sexe',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='admis',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='pension',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='rang',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='sexe',
        ),
    ]
